if __name__ == '__main__':
	op = int()
	while True:
		print("") 
		print("Eliga la provincia a consultar")
		print("   1. Bocas del Toro")
		print("   2. Coclé")
		print("   3. Colon")
		print("   4. Chiriqui")
		print("   5. Darien")
		print("   6. Herrera")
		print("   7. Los Santos")
		print("   8. Panamá")
		print("   9. Panamá oeste")
		print("   10. Veraguas")
		print("   11. Embera-Wounan")
		print("   12. Guna Yala")
		print("   13. Ngobe Bugle")
		print("   14. Salir")
		
		print("Elija una opción (1-14): ")
		op = int(input())
		
		if op==1:
			print("Los ditritos de la provincia de Bocas del Toro son:")
			print(" 1-Distrito de Bocas del Toro")
			print(" 2-Distrito de Almirante")
			print(" 3-Distrito de Changuinola")
			print(" 4-Distrito de Chiriqui Grande")
		elif op==2:
			print("Los ditritos de la provincia de Coclé son:")
			print(" 1-Distrito de Penonome")
			print(" 2-Distrito de Aguadulce")
			print(" 3-Distrito de Anton")
			print(" 4-Distrito La Pintada")
			print(" 5-Distrito de Nata")
			print(" 6-Distrito de Ola")
		elif op==3:
			print("Los ditritos de la provincia de Colon son:")
			print(" 1-Distrito de Colon")
			print(" 2-Distrito de Chagres")
			print(" 3-Distrito de Donoso")
			print(" 4-Distrito de Omar Torrijos Herrera")
			print(" 5-Distrito de Portobelo")
			print(" 6-Distrito de Santa Isabel")
		elif op==4:
			print("Los ditritos de la provincia de Chiriqui son:")
			print(" 1-Distrito de David")
			print(" 2-Distrito de Alanje")
			print(" 3-Distrito de Baru")
			print(" 4-Distrito de Boqueron")
			print(" 5-Distrito de Boquete")
			print(" 6-Distrito de Bugaba")
			print(" 7-Distrito de Dolega")
			print(" 8-Distrito de Gualaca")
			print(" 9-Distrito de Remedios")
			print(" 10-Distrito de Renacimiento")
			print(" 11-Distrito de San Felix")
			print(" 12-Distrito de San Lorenzo")
			print(" 13-Distrito de Tierras Altas")
			print(" 14-Distrito de Tolé")
		elif op==5:
			print("Los ditritos de la provincia de Darien son:")
			print(" 1-Distrito de Chepinaga")
			print(" 2-Distrito de Pinogana")
			print(" 3-Distrito de Santa Fe")
		elif op==6:
			print("Los ditritos de la provincia de Herrera son:")
			print(" 1-Distrito de Chitre")
			print(" 2-Distrito de Las Minas")
			print(" 3-Distrito de Los Pozos")
			print(" 4-Distrito de Ocu")
			print(" 5-Distrito de Parita")
			print(" 6-Distrito de Pese")
			print(" 7-Distrito de Santa Maria")
		elif op==7:
			print("Los ditritos de la provincia de Los Santos son:")
			print(" 1-Distrito de Las Tablas")
			print(" 2-Distrito de Guarare")
			print(" 3-Distrito de Los Santos")
			print(" 4-Distrito de Macaracas")
			print(" 5-Distrito de Pedasia")
			print(" 6-Distrito de Pocri")
			print(" 7-Distrito de Tonosi")
		elif op==8:
			print("Los ditritos de la provincia de Panamá son:")
			print(" 1-Distrito de Panamá")
			print(" 2-Distrito de Balboa")
			print(" 3-Distrito de Chepo")
			print(" 4-Distrito de Chiman")
			print(" 5-Distrito de San Miguelito")
			print(" 6-Distrito de Taboga")
		elif op==9:
			print("Los ditritos de la provincia de Panamá Oeste son:")
			print(" 1-Distrito de La Chorrera")
			print(" 2-Distrito de Arraijan")
			print(" 3-Distrito de Capira")
			print(" 4-Distrito de Cham")
			print(" 5-Distrito de San Carlos")
		elif op==10:
			print("Los ditritos de la provincia de Veraguas son:")
			print(" 1-Distrito de Santiago")
			print(" 2-Distrito de Atalaya")
			print(" 3-Distrito de Calobre")
			print(" 4-Distrito de Cañazas")
			print(" 5-Distrito de La Mesa")
			print(" 6-Distrito de Las Palmas")
			print(" 7-Distrito de Mariato")
			print(" 8-Distrito de Montijo")
			print(" 9-Distrito de Rio de Jesus")
			print(" 10-Distrito de San Frnacisco")
			print(" 11-Distrito de Santa Fe")
			print(" 12-Distrito de Sona")
		elif op==11:
			print("Los ditritos de la Comarca Embera-Wounaan son:")
			print(" 1-Distrito de Cemaco")
			print(" 2-Distrito de Sambu")
		elif op==12:
			print("Los ditritos de la Comarca de Guna Yala son:")
			print(" la comarca de Guna Yala no cuenta con distritos segun el registro del Tribunal Electoral")
		elif op==13:
			print("Los ditritos de la Comarca de Ngobe Bugle son:")
			print(" 1-Distrito de Besikó")
			print(" 2-Distrito de Jirondai")
			print(" 3-Distrito de Kankintú")
			print(" 4-Distrito Kusapín")
			print(" 5-Distrito de Mironó")
			print(" 6-Distrito de Müna")
			print(" 7-Distrito de Nole Duima")
			print(" 8-Distrito de  Ñürüm")
			print(" 9-Distrito de Santa Catalina o Calovébora")
		elif op==14:
			print("Gracias, vuelva pronto")
		else:
			print("Opción no válida")
		print("Presione enter para continuar")
		input() 
		if op==14: break

